export const CardData = [
    {
      imgsrc: "https://www.nicepng.com/png/detail/366-3668595_apple-ipad-air-ipad-air-2-wi-fi.png",
      title: "Apple Ipad Air 2",
      text1: "Operating System : iOS 8.1",
      text2: "Screen Size : 9.7 inches",
      text3: "RAM : 1GB",
      text4: "Storage : 128GB",
      text5: "Processor : 1.3GHz Dual-Core",
      text6: "Battery : 8600mAh",
      text7: "Price : $ 383.23/-",
      btnText: "Add To Cart",
    },
    {
      imgsrc: "https://images-na.ssl-images-amazon.com/images/I/51Ch-ZgIoFL.jpg",  
      title: "Samsung S20 Ultra 5G",
      text1: "Operating System : Android 10 OS",
      text2: "Screen Size : 6.9 Inches",
      text3: "RAM : 12GB",
      text4: "Storage : 128GB",
      text5: "Processor : 2.7GHz Octa-Core",
      text6: "Battery : 5000mAh",
      text7: "Price : $ 1,225.27/-",
      btnText: "Add To Cart",
    },
    {
        imgsrc: "https://c1.neweggimages.com/ProductImage/83-360-021-10.jpg",
        title: "Gaming PC",
        text1: "CPU : Ryzen 7 3rd Gen 3700X 3.60GHz",
        text2: "RAM : 16GB",
        text3: "Hard Disk : 1TB SSD",
        text4: "Card : NVIDIA GeForce RTX 3060 Ti 8GB",
        text5: "Operating System : Windows 10 Home",
        text6: "Color : Black",
        text7: "Price : £ 1,610.39/-",
        btnText: "Add To Cart",
    },
    {
        imgsrc: "https://asia-exstatic-vivofs.vivo.com/PSee2l50xoirPK7y/1631102129760/bd1aeac29402138967fb57443460e742.png",
        title: "Vivo X70 Pro",
        text1: "Operating System : Android 11 OS",
        text2: "Screen Size : 6. Inches",
        text3: "RAM : 12GB",
        text4: "Storage : 256GB",
        text5: "Processor : 2.8GHz Octa-Core",
        text6: "Battery : 4450mAh",
        text7: "Price : $ 868/-",
        btnText: "Add To Cart",
    },
    {
        imgsrc: "https://d10mhq06fikmnr.cloudfront.net/catalog/product/s/h/sharkoon-slider-rgb_white_main_1.jpg",
        title: "Gaming PC",
        text1: "CPU : AMD 3700X 4.4 GHz ",
        text2: "RAM : 16GB",
        text3: "Hard Disk : 1TB SSD",
        text4: "Card : Nvidia GeForce RTX 3070 ",
        text5: "Operating System : Windows 10 Home",
        text6: "Color : White",
        text7: "Price : $ 1940.00/-",
        btnText: "Add To Cart",
    },
    {
        imgsrc: "https://qph.fs.quoracdn.net/main-qimg-36a86584fc893a7f9b8135639ed74545-lq",
        title: "Apple 21.5",
        text1: "CPU : 2.7 GHz Quad-Core ",
        text2: "RAM : 8GB",
        text3: "Hard Disk : 1TB",
        text4: "Card : nVIDIA GeForce GT 640M Graphics",
        text5: "Operating System : OSX",
        text6: "Color : Silver",
        text7: "Price : $ 673.98/-",
        btnText: "Add To Cart",
    },
  ];